# Generated by Django 5.0.6 on 2024-06-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buscar_rival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cancha', models.CharField(max_length=20)),
                ('hora_reserva', models.IntegerField()),
                ('dia_reserva', models.IntegerField()),
                ('tu_equipo', models.CharField(max_length=20)),
                ('numero_celular', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inicia_sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('numero_celular', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reservar_cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('numero_celular', models.IntegerField()),
                ('nombre_cancha', models.CharField(max_length=20)),
                ('hora_reserva', models.IntegerField()),
                ('dia_reserva', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservar_Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('numero_celular', models.IntegerField()),
                ('nombre_cancha', models.CharField(max_length=20)),
                ('hora_reserva', models.IntegerField()),
                ('cantidad_horas', models.IntegerField(max_length=20)),
                ('dia_reserva', models.IntegerField()),
                ('tipo_evento', models.CharField(max_length=20)),
            ],
        ),
    ]
