# Generated by Django 5.0.6 on 2024-07-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservarevento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('numero_celular', models.IntegerField()),
                ('nombre_cancha', models.CharField(max_length=20)),
                ('hora_reserva', models.IntegerField()),
                ('cantidad_horas', models.IntegerField()),
                ('dia_reserva', models.IntegerField()),
                ('tipo_evento', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Buscar_rival',
            new_name='Buscarrival',
        ),
        migrations.RenameModel(
            old_name='Reservar_cancha',
            new_name='Reservarcancha',
        ),
        migrations.DeleteModel(
            name='Reservar_Evento',
        ),
    ]
