# Generated by Django 5.0.6 on 2024-07-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0002_reservarevento_rename_buscar_rival_buscarrival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscarrival',
            name='dia_reserva',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='buscarrival',
            name='hora_reserva',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inicia_sesion',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservarcancha',
            name='dia_reserva',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservarcancha',
            name='hora_reserva',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservarcancha',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservarevento',
            name='dia_reserva',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservarevento',
            name='hora_reserva',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservarevento',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
