# Generated by Django 5.0.6 on 2024-07-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0003_alter_buscarrival_dia_reserva_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buscarrival',
            options={'ordering': ['dia_reserva', 'hora_reserva'], 'verbose_name': 'Buscar rival'},
        ),
        migrations.AlterModelOptions(
            name='reservarcancha',
            options={'ordering': ['dia_reserva', 'hora_reserva'], 'verbose_name': 'Cancha reservada', 'verbose_name_plural': 'Canchas reservadas'},
        ),
        migrations.AlterModelOptions(
            name='reservarevento',
            options={'ordering': ['dia_reserva', 'hora_reserva'], 'verbose_name': 'Reserva de evento'},
        ),
        migrations.RemoveField(
            model_name='reservarevento',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='reservarevento',
            name='numero_celular',
        ),
    ]
